# Generated by gn_to_cmake.py.
cmake_minimum_required(VERSION 2.8.8 FATAL_ERROR)
cmake_policy(VERSION 2.8.8)
enable_language(ASM)

add_definitions(-DSDL_VIDEO_DRIVER_COCOA=1)


#//:compile_processors
set("target" "compile_processors")
set("${target}__cxx_srcs" "/mywork/github/skia/cmake/empty.cpp")
add_custom_target("${target}" SOURCES ${${target}__cxx_srcs})

include(cmake_raw.cmake)
include(cmake_skia.cmake)
include(cmake_sk_app.cmake)




