#//third_party/libjpeg-turbo:libjpeg
set("target" "third_party__libjpeg-turbo_libjpeg")
list(APPEND "${target}__c_srcs"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jaricom.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jcapimin.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jcapistd.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jcarith.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jccoefct.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jccolor.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jcdctmgr.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jchuff.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jcinit.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jcmainct.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jcmarker.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jcmaster.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jcomapi.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jcparam.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jcphuff.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jcprepct.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jcsample.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jdapimin.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jdapistd.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jdarith.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jdcoefct.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jdcolor.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jddctmgr.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jdhuff.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jdinput.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jdmainct.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jdmarker.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jdmaster.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jdmerge.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jdphuff.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jdpostct.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jdsample.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jerror.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jfdctflt.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jfdctfst.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jfdctint.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jidctflt.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jidctfst.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jidctint.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jidctred.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jmemmgr.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jmemnobs.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jquant1.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jquant2.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jutils.c"
        "/mywork/github/skia/third_party/externals/libjpeg-turbo/jsimd_none.c")
add_library("${target}" OBJECT ${${target}__c_srcs})
set_target_properties("${target}" PROPERTIES COMPILE_DEFINITIONS "TURBO_FOR_WINDOWS;")
set_target_properties("${target}" PROPERTIES COMPILE_FLAGS "-w -fstrict-aliasing -fPIC -Werror -fvisibility=hidden -Wno-unused-parameter -g -isystem /mywork/github/skia/third_party/libjpeg-turbo -isystem /mywork/github/skia/third_party/externals/libjpeg-turbo ")
set_target_properties("${target}" PROPERTIES LINK_FLAGS "-Wl,-w ")
