
#//:fuzz
set("target" "fuzz")
list(APPEND "${target}__cxx_srcs"
        "/mywork/github/skia/fuzz/FuzzCanvas.cpp"
        "/mywork/github/skia/fuzz/FuzzCommon.cpp"
        "/mywork/github/skia/fuzz/FuzzDrawFunctions.cpp"
        "/mywork/github/skia/fuzz/FuzzEncoders.cpp"
        "/mywork/github/skia/fuzz/FuzzGradients.cpp"
        "/mywork/github/skia/fuzz/FuzzParsePath.cpp"
        "/mywork/github/skia/fuzz/FuzzPathMeasure.cpp"
        "/mywork/github/skia/fuzz/FuzzPathop.cpp"
        "/mywork/github/skia/fuzz/FuzzPolyUtils.cpp"
        "/mywork/github/skia/fuzz/FuzzRegionOp.cpp"
        "/mywork/github/skia/fuzz/fuzz.cpp"
        "/mywork/github/skia/fuzz/oss_fuzz/FuzzAnimatedImage.cpp"
        "/mywork/github/skia/fuzz/oss_fuzz/FuzzImage.cpp"
        "/mywork/github/skia/fuzz/oss_fuzz/FuzzImageFilterDeserialize.cpp"
        "/mywork/github/skia/fuzz/oss_fuzz/FuzzJSON.cpp"
        "/mywork/github/skia/fuzz/oss_fuzz/FuzzPathDeserialize.cpp"
        "/mywork/github/skia/fuzz/oss_fuzz/FuzzRegionDeserialize.cpp"
        "/mywork/github/skia/fuzz/oss_fuzz/FuzzRegionSetPath.cpp"
        "/mywork/github/skia/fuzz/oss_fuzz/FuzzTextBlobDeserialize.cpp"
        "/mywork/github/skia/tools/UrlDataManager.cpp"
        "/mywork/github/skia/tools/debugger/SkDebugCanvas.cpp"
        "/mywork/github/skia/tools/debugger/SkDrawCommand.cpp"
        "/mywork/github/skia/tools/debugger/SkJsonWriteBuffer.cpp"
        "/mywork/github/skia/tools/picture_utils.cpp")
list(APPEND "${target}__obj_target_srcs"
        "$<TARGET_OBJECTS:modules__skottie>"
        "$<TARGET_OBJECTS:gpu_tool_utils>"
        "$<TARGET_OBJECTS:flags>"
        "$<TARGET_OBJECTS:third_party__zlib>"
        "$<TARGET_OBJECTS:third_party__libpng>"
        "$<TARGET_OBJECTS:third_party__zlib_zlib_x86>"
        "$<TARGET_OBJECTS:modules__sksg>"
        "$<TARGET_OBJECTS:third_party__jsoncpp>"
        "$<TARGET_OBJECTS:modules__skottie_fuzz>")
add_executable("${target}" ${${target}__cxx_srcs} ${${target}__obj_target_srcs})
set_property(TARGET "${target}" APPEND PROPERTY INCLUDE_DIRECTORIES
        "/mywork/github/skia/tools/"
        "/mywork/github/skia/tools/debugger/"
        "/mywork/github/skia/include/private/"
        "/mywork/github/skia/src/c/"
        "/mywork/github/skia/src/codec/"
        "/mywork/github/skia/src/core/"
        "/mywork/github/skia/src/effects/"
        "/mywork/github/skia/src/fonts/"
        "/mywork/github/skia/src/image/"
        "/mywork/github/skia/src/images/"
        "/mywork/github/skia/src/lazy/"
        "/mywork/github/skia/src/opts/"
        "/mywork/github/skia/src/pathops/"
        "/mywork/github/skia/src/pdf/"
        "/mywork/github/skia/src/ports/"
        "/mywork/github/skia/src/sfnt/"
        "/mywork/github/skia/src/shaders/"
        "/mywork/github/skia/src/shaders/gradients/"
        "/mywork/github/skia/src/sksl/"
        "/mywork/github/skia/src/utils/"
        "/mywork/github/skia/src/utils/win/"
        "/mywork/github/skia/src/xml/"
        "/mywork/github/skia/third_party/gif/"
        "/mywork/github/skia/src/gpu/"
        "/mywork/github/skia/tools/flags/"
        "/mywork/github/skia/tools/gpu/"
        "/mywork/github/skia/include/android/"
        "/mywork/github/skia/include/c/"
        "/mywork/github/skia/include/codec/"
        "/mywork/github/skia/include/config/"
        "/mywork/github/skia/include/core/"
        "/mywork/github/skia/include/effects/"
        "/mywork/github/skia/include/encode/"
        "/mywork/github/skia/include/gpu/"
        "/mywork/github/skia/include/atlastext/"
        "/mywork/github/skia/include/pathops/"
        "/mywork/github/skia/include/ports/"
        "/mywork/github/skia/include/svg/"
        "/mywork/github/skia/include/utils/"
        "/mywork/github/skia/include/utils/mac/"
        "/mywork/github/skia/include/atlastext/"
        "/mywork/github/skia/modules/skottie/include/")
set_target_properties("${target}" PROPERTIES COMPILE_DEFINITIONS "SK_GAMMA_APPLY_TO_A8;SK_ENABLE_DISCRETE_GPU;GR_TEST_UTILS=1;SK_ENABLE_SPIRV_VALIDATION;SK_HAS_HEIF_LIBRARY;SK_HAS_JPEG_LIBRARY;SK_SUPPORT_PDF;SK_PDF_USE_SFNTLY;SK_HAS_PNG_LIBRARY;SK_CODEC_DECODES_RAW;SK_HAS_WEBP_LIBRARY;SK_XML;SK_SUPPORT_ATLAS_TEXT=1;SK_ENABLE_SKOTTIE;")
set_target_properties("${target}" PROPERTIES COMPILE_FLAGS "-fstrict-aliasing -fPIC -Werror -fvisibility=hidden -Wall -Wextra -Winit-self -Wpointer-arith -Wsign-compare -Wvla -Wno-deprecated-declarations -Wno-maybe-uninitialized -Weverything -Wno-unknown-warning-option -Wno-nonportable-include-path -Wno-nonportable-system-include-path -Wno-cast-align -Wno-cast-qual -Wno-conversion -Wno-disabled-macro-expansion -Wno-documentation -Wno-documentation-unknown-command -Wno-double-promotion -Wno-exit-time-destructors -Wno-float-equal -Wno-format-nonliteral -Wno-global-constructors -Wno-missing-prototypes -Wno-missing-variable-declarations -Wno-pedantic -Wno-reserved-id-macro -Wno-shadow -Wno-shift-sign-overflow -Wno-signed-enum-bitfield -Wno-switch-enum -Wno-undef -Wno-unreachable-code -Wno-unreachable-code-break -Wno-unreachable-code-return -Wno-unused-macros -Wno-unused-member-function -Wno-unused-template -Wno-zero-as-null-pointer-constant -Wno-bad-function-cast -Wno-covered-switch-default -Wno-deprecated -Wno-missing-noreturn -Wno-old-style-cast -Wno-padded -Wno-newline-eof -Wno-implicit-fallthrough -Wno-unused-parameter -g -isystem /mywork/github/skia/third_party/externals/jsoncpp/include -isystem /mywork/github/skia/third_party/libpng -isystem /mywork/github/skia/third_party/externals/libpng -std=c++14 -fvisibility-inlines-hidden -fno-exceptions -fno-rtti -Wnon-virtual-dtor -Wno-noexcept-type -Wno-abstract-vbase-init -Wno-weak-vtables -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-undefined-func-template ")
set_target_properties("${target}" PROPERTIES LINK_FLAGS "-Wl,-rpath,@loader_path/. -Wl,-w ")
find_library("library__dl" "dl")
find_library("library__AppKit" "AppKit")
find_library("library__ApplicationServices" "ApplicationServices")
find_library("library__OpenGL" "OpenGL")
target_link_libraries("${target}"
        "skia"
        "${library__dl}"
        "${library__AppKit}"
        "${library__ApplicationServices}"
        "${library__OpenGL}")

